server:
  port: 8888

spring:
  application:
    name: comfig-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/MehmetSimsek33/microservice-config-server.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "mehmetsimsek33"
          password: ${GİT_KEY}
