server:
  port: 9091
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongoadmin
      password: secret
      authentication-database: admin
      database: testdb
